=== dziegenh/XSD_GUI/src/main/resources/config/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="ns">

	<xs:complexType name="SystemElementType">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="id" type="xs:int" use="required" />
	</xs:complexType>

	<xs:complexType name="NodeListType">
		<xs:sequence>
			<xs:element name="module" type="ModuleType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="SmartNodeListType">
		<xs:complexContent>
			<xs:extension base="NodeListType">
				<xs:sequence>
					<xs:element name="node" type="NodeType" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="smartNode" type="SmartNodeType" minOccurs="0" maxOccurs="unbounded" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="NodeType">
		<xs:complexContent>
			<xs:extension base="SystemElementType">
				<xs:all>
					<xs:element name="children" type="NodeListType"/>
				</xs:all>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="SmartNodeType">
		<xs:complexContent>
			<xs:extension base="SystemElementType">
				<xs:all>
					<xs:element name="children" type="SmartNodeListType"/>
				</xs:all>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


	<xs:complexType name="SlaveNodeListType">
		<xs:sequence>
			<xs:element name="node" type="NodeType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="smartNode" type="SmartNodeType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ModuleType">
		<xs:complexContent>
			<xs:extension base="SystemElementType">
				<xs:attribute name="parameterFile" type="xs:string" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


	<xs:complexType name="ConfigurationType">
		<xs:attribute name="cycleTime" type="xs:double" use="required" />
		<xs:attribute name="profiling" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="logDir" type="xs:string" use="optional" default="../log/"/>
		<xs:attribute name="logLevel" type="xs:string" use="optional" default="DEBUG"/>
		<xs:attribute name="noLog" type="xs:boolean" use="optional" default="false"/>
	</xs:complexType>


	<xs:complexType name="MockUpConfiguration">
		<xs:complexContent>
			<xs:extension base="ConfigurationType">
				<xs:attribute name="binary" type="xs:string" use="required" />
				<xs:attribute name="shutdownCycles" type="xs:int" use="optional" default="5">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:maxInclusive value="255"/>
							<xs:minInclusive value="0"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="baudRate" type="xs:int" use="optional" default="1000000">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:maxInclusive value="3000000"/>
							<xs:minExclusive value="9600"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="NodeserverType">
		<xs:all>
			<xs:element name="children" type="SlaveNodeListType" />
			<xs:element name="configuration" type="ConfigurationType" />
		</xs:all>
	</xs:complexType>
	<xs:element name="Nodeserver" type="NodeserverType"/>



</xs:schema>

=== dziegenh/XSD_GUI/src/main/resources/config/mockUpNs.xml
<?xml version="1.0"?>
<Nodeserver xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="ns"
            xsi:noNamespaceSchemaLocation="schema.xsd">
    <configuration cycleTime="5" profiling="false" />
    <children>
        <node name="simpleSlave" id="0">
            <children>
                <module name="DigitalIO" id="0" parameterFile="./modules/DigitalIO.xml"/>
                <module name="PWM" id="0" parameterFile="./modules/PWM.xml" />
                <module name="ADC" id="0" parameterFile="./modules/ADC.xml" />
                <module name="Debug" id="0" parameterFile="./modules/Debug.xml"/>
                <module name="SystemConfig" id="0"  parameterFile="./modules/SystemConfig.xml" />
            </children>
        </node>
    </children>
</Nodeserver>
